version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  nestjs-app:
    build: .
    container_name: nestjs-app
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/mydatabase?schema=public 
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app 

volumes:
  db_data:
